apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-app
  namespace: argocd
spec:
  destination:
    namespace: hive
    server: https://kubernetes.default.svc
  project: default
  source:
    path: hive/defs
    repoURL: https://github.com/pjanouse/ocp-cfg.git
    targetRevision: main
  syncPolicy:
    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
#  ignoreDifferences:
#  - group: apps.openshift.io
#    kind: DeploymentConfig
#    jsonPointers:
#    - /spec/install/spec/deployments[0]/spec/template/spec/containers[0]/ports
