apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hive-operator
  namespace: hive
spec:
  channel: alpha
  name: hive-operator
  source: community-operators
  sourceNamespace: openshift-marketplace

