apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olm
resources:
- https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.22.0/crds.yaml
- https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.22.0/olm.yaml